/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jirniy_Kot (https://sketchfab.com/Jirniy_Kot)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/quick-knife-c902cb0f4ee2479297b016161d6b28fa
title: Quick knife
*/

import { useGLTF, useAnimations } from "@react-three/drei";
import useStore from "stores/defaultStore";
import { useRef, useState } from "react";
import { useFrame } from "@react-three/fiber";

import { useSpring, animated } from "@react-spring/three";

export default function ModelKnives({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./models/knives/scene.gltf");
  const { actions } = useAnimations(animations, group);

  const rotationY = useStore((state) => state.Model.rotationY);
  const rotationX = useStore((state) => state.Model.rotationX);

  const CloseKnives = useStore((state) => state.Model.CloseKnives);

  const mesh = actions;
  useFrame(() => (rotationX ? (mesh.current.rotation.x += 0.01) : ""));
  useFrame(() => (rotationY ? (mesh.current.rotation.y += 0.01) : ""));

  /* use spring */
  const [active, setActive] = useState(0);
  const rotation = useSpring({
    from: {
      rotation: [0, 0, 0],
    },
    to: {
      rotation: CloseKnives ? [0, 0, 0] : [0, 0, Math.PI - 0.2],
    },
  });

  return (
    <group ref={mesh} {...props} dispose={null} position={[5, 5, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-1.81, 0.03, 0.36]} rotation={[Math.PI / 2, 0, 0]}>
          <group name="Blade" position={[-0.94, 0.08, 0.31]}>
            <animated.mesh
              ref={mesh}
              geometry={nodes.Blade_0.geometry}
              material={materials.BLADE}
              rotation={rotation.rotation}
            >
              <meshStandardMaterial color={"lightgreen"} roughness={0.3} metalness={1} />
            </animated.mesh>
          </group>
          <group position={[-0.32, 0.24, 0]}>
            <mesh geometry={nodes.Ruchka_0.geometry} material={materials.RUBBER} />

            <mesh geometry={nodes.Ruchka_1.geometry} material={materials.IRON} />

            <mesh geometry={nodes.Ruchka_2.geometry} material={materials.UZOR}>
              {" "}
              <meshStandardMaterial color={"lightgreen"} roughness={0.3} metalness={1} />
            </mesh>
            <mesh geometry={nodes.Ruchka_3.geometry} material={materials.zatemnen} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/knives/scene.gltf");
